// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Call struct {
	CallID                 int64
	CallGroupID            *int32
	SystemID               int
	SiteID                 *int32
	Tgid                   int
	TrCallID               *string
	CallNum                *int32
	StartTime              pgtype.Timestamptz
	StopTime               pgtype.Timestamptz
	Duration               *float32
	Freq                   *int64
	FreqError              *int32
	SignalDb               *float32
	NoiseDb                *float32
	ErrorCount             *int32
	SpikeCount             *int32
	AudioType              *string
	AudioFilePath          *string
	AudioFileSize          *int32
	CallFilename           *string
	Phase2Tdma             *bool
	TdmaSlot               *int16
	Analog                 *bool
	Conventional           *bool
	Encrypted              *bool
	Emergency              *bool
	CallState              *int16
	CallStateType          *string
	MonState               *int16
	MonStateType           *string
	RecState               *int16
	RecStateType           *string
	RecNum                 *int16
	SrcNum                 *int16
	ProcessCallTime        *float32
	RetryAttempt           *int16
	PatchedTgids           []int
	SystemName             *string
	SiteShortName          *string
	TgAlphaTag             *string
	TgDescription          *string
	TgTag                  *string
	TgGroup                *string
	HasTranscription       bool
	TranscriptionStatus    string
	TranscriptionText      *string
	TranscriptionWordCount *int32
	SrcList                []byte
	FreqList               []byte
	UnitIds                []int
	MetadataJson           []byte
	Incidentdata           []byte
	InstanceID             *string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

// Crash recovery snapshots. Retention: 7 days. Purge: DELETE WHERE snapshot_time < now() - interval '7 days'.
type CallActiveCheckpoint struct {
	ID           int
	InstanceID   *string
	SnapshotTime pgtype.Timestamptz
	ActiveCalls  []byte
	CallCount    *int32
}

type CallFrequency struct {
	ID            int64
	CallID        int64
	CallStartTime pgtype.Timestamptz
	Freq          int64
	Time          pgtype.Timestamptz
	Pos           *float32
	Len           *float32
	ErrorCount    *int32
	SpikeCount    *int32
}

type CallGroup struct {
	ID        int
	SystemID  int
	Tgid      int
	StartTime pgtype.Timestamptz
	// Best-quality call_id for this group. Soft FK — not enforced by constraint since it references a partitioned table without the partition key.
	PrimaryCallID       *int64
	TgAlphaTag          *string
	TgDescription       *string
	TgTag               *string
	TgGroup             *string
	TranscriptionText   *string
	TranscriptionStatus *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CallTransmission struct {
	ID            int64
	CallID        int64
	CallStartTime pgtype.Timestamptz
	Src           int
	Time          pgtype.Timestamptz
	Pos           *float32
	Duration      *float32
	Emergency     *int16
	SignalSystem  *string
	Tag           *string
}

// TR console log. Retention: 30 days. Purge: DELETE WHERE log_time < now() - interval '30 days'.
type ConsoleMessage struct {
	ID            int64
	InstanceID    *string
	LogTime       pgtype.Timestamptz
	Severity      *string
	LogMsg        *string
	MqttTimestamp pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type DataFixup struct {
	Name      string
	AppliedAt pgtype.Timestamptz
	Detail    []byte
}

// Decode rate snapshots. Decimation: 1/min after 1 week, 1/hour after 1 month. Run: SELECT decimate_state_table('decode_rates', 'time').
type DecodeRate struct {
	ID                 int64
	SystemID           *int32
	DecodeRate         *float32
	DecodeRateInterval *float32
	ControlChannel     *int64
	SysNum             *int16
	SysName            *string
	Time               pgtype.Timestamptz
	InstanceID         *string
}

type Instance struct {
	ID          int
	InstanceID  string
	InstanceKey *string
	FirstSeen   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type InstanceConfig struct {
	ID           int
	InstanceID   *string
	CaptureDir   *string
	UploadServer *string
	CallTimeout  *float32
	LogFile      *string
	InstanceKey  *string
	ConfigJson   []byte
	Time         pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// Raw MQTT archive. Retention: 7 days. Drop weekly partitions older than 7d.
type MqttRawMessage struct {
	ID           int64
	Topic        string
	Payload      []byte
	ReceivedAt   pgtype.Timestamptz
	InstanceID   *string
	Processed    bool
	ProcessError *string
}

type PgStatUserTable struct {
	Relname  *string
	NLiveTup *int64
}

// Plugin status log. Retention: 30 days. Purge: DELETE WHERE time < now() - interval '30 days'.
type PluginStatus struct {
	ID         int64
	ClientID   *string
	InstanceID *string
	Status     *string
	Time       pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Recorder state snapshots. Decimation: 1/min after 1 week, 1/hour after 1 month. Run: SELECT decimate_state_table('recorder_snapshots', 'time').
type RecorderSnapshot struct {
	ID           int64
	InstanceID   *string
	RecorderID   *string
	SrcNum       *int16
	RecNum       *int16
	Type         *string
	RecState     *int16
	RecStateType *string
	Freq         *int64
	Duration     *float32
	Count        *int32
	Squelched    *bool
	Time         pgtype.Timestamptz
}

type ScanCursor struct {
	Name      string
	LastID    int64
	UpdatedAt pgtype.Timestamptz
}

type Site struct {
	SiteID        int
	SystemID      int
	InstanceID    string
	ShortName     string
	SysNum        *int16
	Nac           *string
	Rfss          *int16
	P25SiteID     *int16
	SystemTypeRaw *string
	FirstSeen     pgtype.Timestamptz
	LastSeen      pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type System struct {
	SystemID   int
	SystemType string
	Name       *string
	Sysid      string
	Wacn       string
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SystemMergeLog struct {
	ID               int
	SourceID         int
	TargetID         int
	CallsMoved       *int32
	TalkgroupsMoved  *int32
	TalkgroupsMerged *int32
	UnitsMoved       *int32
	UnitsMerged      *int32
	EventsMoved      *int32
	PerformedAt      pgtype.Timestamptz
	PerformedBy      *string
}

type Talkgroup struct {
	SystemID       int
	Tgid           int
	AlphaTag       *string
	AlphaTagSource *string
	Tag            *string
	Group          *string
	Description    *string
	Mode           *string
	Priority       *int32
	FirstSeen      pgtype.Timestamptz
	LastSeen       pgtype.Timestamptz
	SearchVector   interface{}
	CallCount30d   int
	Calls1h        int
	Calls24h       int
	UnitCount30d   int
	StatsUpdatedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TalkgroupDirectory struct {
	SystemID     int
	Tgid         int
	AlphaTag     *string
	Mode         *string
	Description  *string
	Tag          *string
	Category     *string
	Priority     *int32
	SearchVector interface{}
	ImportedAt   pgtype.Timestamptz
}

type Transcription struct {
	ID            int
	CallID        int64
	CallStartTime pgtype.Timestamptz
	Text          *string
	Source        string
	IsPrimary     bool
	Confidence    *float32
	Language      *string
	Model         *string
	Provider      *string
	WordCount     *int32
	DurationMs    *int32
	ProviderMs    *int32
	Words         []byte
	SearchVector  interface{}
	CreatedAt     pgtype.Timestamptz
}

type TrunkingMessage struct {
	ID           int64
	SystemID     *int32
	SysNum       *int16
	SysName      *string
	TrunkMsg     *int32
	TrunkMsgType *string
	Opcode       *string
	OpcodeType   *string
	OpcodeDesc   *string
	Meta         []byte
	Time         pgtype.Timestamptz
	InstanceID   *string
}

type Unit struct {
	SystemID             int
	UnitID               int
	AlphaTag             *string
	AlphaTagSource       *string
	FirstSeen            pgtype.Timestamptz
	LastSeen             pgtype.Timestamptz
	LastEventType        *string
	LastEventTime        pgtype.Timestamptz
	LastEventTgid        *int32
	RecorderAlphaTag     *string
	RecorderAlphaTagSeen pgtype.Timestamptz
	OtaAlphaTag          *string
	OtaAlphaTagFirstSeen pgtype.Timestamptz
	OtaAlphaTagLastSeen  pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type UnitEvent struct {
	ID                   int64
	EventType            string
	SystemID             int
	UnitRid              int
	Time                 pgtype.Timestamptz
	Tgid                 *int32
	UnitAlphaTag         *string
	TgAlphaTag           *string
	CallNum              *int32
	Freq                 *int64
	StartTime            pgtype.Timestamptz
	StopTime             pgtype.Timestamptz
	Encrypted            *bool
	Emergency            *bool
	Position             *float32
	Length               *float32
	ErrorCount           *int32
	SpikeCount           *int32
	SampleCount          *int32
	TransmissionFilename *string
	TalkgroupPatches     []int
	InstanceID           *string
	SysNum               *int16
	SysName              *string
	MetadataJson         []byte
	Incidentdata         []byte
}

type UnitTagSuggestion struct {
	ID                int64
	SystemID          int
	UnitID            int
	TagKey            string
	ProposedTag       string
	Status            string
	Occurrences       int
	CallCount         int
	MatchesCurrentTag bool
	TagAtSighting     *string
	FirstSeen         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	Evidence          []byte
	AppliedTag        *string
	PreviousTag       *string
	PreviousTagSource *string
	DecidedAt         pgtype.Timestamptz
	DecidedBy         *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
